#!/usr/bin/env python3
"""
otp.py — One-Time Pad Encryption / Decryption

Implements the mathematically perfect-secrecy cipher described by Shannon:

    M = [m1, m2, ..., mn]      each m_i in [0, 255]   (extended ASCII / raw byte)
    K = [k1, k2, ..., kn]      TRULY RANDOM, same length as M, used ONCE
    C = (M + K) mod 256        encryption (elementwise)
    M = (C - K) mod 256        decryption (elementwise)

WHY THIS IS "UNBREAKABLE":
    Shannon's 1949 proof of perfect secrecy shows that if K is truly
    random, kept secret, used only once, and is at least as long as M,
    then for ANY ciphertext C, EVERY possible plaintext M' of the same
    length is an equally likely candidate. The ciphertext carries zero
    statistical information about the plaintext. This isn't a claim
    about computational hardness (like AES or RSA), which is what
    "hard for an AI/computer to crack" would mean — it's a claim of
    information-theoretic security: there is no attack, no matter how
    much compute or intelligence (human, classical AI, or even a
    hypothetical future superintelligence) is thrown at it, because the
    information needed to distinguish plaintexts simply is not present
    in the ciphertext.

    This guarantee holds ONLY if every condition below is met. Break
    any one of them and you no longer have an OTP — you have a
    (probably weak) stream cipher.

STRICT REQUIREMENTS FOR THE GUARANTEE TO HOLD:
    1. The key must be generated by a TRUE random source (this code
       uses Python's `secrets` module, which draws from the OS CSPRNG /
       hardware entropy — NOT `random`, which is a deterministic PRNG
       and would silently destroy the security guarantee).
    2. The key must be AT LEAST as long as the message (padding or
       truncation breaks the proof).
    3. The key must NEVER be reused, in whole or in part, for another
       message. Reusing a key leaks information (this is exactly how
       the real-world VENONA project broke Soviet OTP traffic in the
       1940s — not through cryptanalysis of the math, but key reuse).
    4. The key must be exchanged and stored with at least as much
       security as the message itself, and destroyed after use.
    5. The key must be kept fully secret from any adversary.

    This program enforces (1) and (2) in code and will refuse to
    encrypt/decrypt on a length mismatch. Requirements (3), (4), and
    (5) are operational/human responsibilities that no software can
    fully guarantee for you — they are noted prominently in the CLI
    and the accompanying web interface.

USAGE (CLI):
    Generate a key (hex-encoded, printed to stdout):
        python otp.py genkey --length 32

    Encrypt a message with a given hex key:
        python otp.py encrypt --message "HELLO WORLD" --key-hex <hex>

    Encrypt and auto-generate a fresh key:
        python otp.py encrypt --message "HELLO WORLD"

    Decrypt:
        python otp.py decrypt --cipher-hex <hex> --key-hex <hex>
"""

import argparse
import secrets
import sys


class OTPError(Exception):
    """Raised for OTP usage/validation errors (e.g. length mismatch)."""
    pass


def generate_key(length: int) -> bytes:
    """
    Generate a TRULY random key of the given length in bytes, using the
    operating system's cryptographically secure random source
    (secrets.token_bytes -> os.urandom under the hood).

    """
    if length <= 0:
        raise OTPError("Key length must be a positive integer.")
    return secrets.token_bytes(length)


def _validate_lengths(data: bytes, key: bytes) -> None:
    if len(key) < len(data):
        raise OTPError(
            f"Key is shorter than the data ({len(key)} < {len(data)} bytes). "
            "A one-time pad key must be at least as long as the message, "
            "or the perfect-secrecy guarantee does not hold."
        )


def encrypt(message: bytes, key: bytes) -> bytes:
    """
    C = (M + K) mod 256, applied byte-by-byte.

    `message` may be any bytes (already-encoded text, or raw binary).
    `key` must be >= len(message) and, for a true OTP, exactly equal to
    len(message) and never reused.
    """
    _validate_lengths(message, key)
    return bytes((m + k) % 256 for m, k in zip(message, key))


def decrypt(ciphertext: bytes, key: bytes) -> bytes:
    """
    M = (C - K) mod 256, applied byte-by-byte.
    """
    _validate_lengths(ciphertext, key)
    return bytes((c - k) % 256 for c, k in zip(ciphertext, key))


def encrypt_text(message: str, key: bytes, encoding: str = "latin-1") -> bytes:
    """
    Encode a text message to bytes and encrypt it.

    Default encoding is latin-1 (a.k.a. ISO-8859-1) because it maps
    code points 0-255 directly onto a single byte each — matching the
    "extended ASCII, values 0-255" model in the spec exactly. Use
    'utf-8' instead if you need full Unicode support (in which case a
    character may take more than one byte, and the key just needs to
    be at least that many bytes long).
    """
    data = message.encode(encoding)
    return encrypt(data, key)


def decrypt_to_text(ciphertext: bytes, key: bytes, encoding: str = "latin-1") -> str:
    data = decrypt(ciphertext, key)
    return data.decode(encoding)


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def _print_warning(key_reused_hint: bool = False) -> None:
    msg = (
        "\n[!] REMINDER: A one-time pad key must be used EXACTLY ONCE, kept\n"
        "    as secret as the message itself, and destroyed after use.\n"
        "    Reusing a key for a second message breaks the security\n"
        "    guarantee completely.\n"
    )
    print(msg, file=sys.stderr)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="One-Time Pad (OTP) encryption/decryption — perfect secrecy per Shannon (1949)."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_gen = sub.add_parser("genkey", help="Generate a truly random key.")
    p_gen.add_argument("--length", type=int, required=True, help="Key length in bytes.")

    p_enc = sub.add_parser("encrypt", help="Encrypt a message.")
    p_enc.add_argument("--message", type=str, required=True, help="Plaintext message.")
    p_enc.add_argument(
        "--key-hex", type=str, default=None,
        help="Hex-encoded key. If omitted, a fresh random key is generated and printed."
    )
    p_enc.add_argument(
        "--encoding", type=str, default="latin-1",
        help="Text encoding for the message (default: latin-1, i.e. 0-255 per char)."
    )

    p_dec = sub.add_parser("decrypt", help="Decrypt a ciphertext.")
    p_dec.add_argument("--cipher-hex", type=str, required=True, help="Hex-encoded ciphertext.")
    p_dec.add_argument("--key-hex", type=str, required=True, help="Hex-encoded key.")
    p_dec.add_argument(
        "--encoding", type=str, default="latin-1",
        help="Text encoding to decode the recovered bytes as (default: latin-1)."
    )

    args = parser.parse_args()

    try:
        if args.command == "genkey":
            key = generate_key(args.length)
            print(key.hex())
            _print_warning()

        elif args.command == "encrypt":
            message_bytes = args.message.encode(args.encoding)
            if args.key_hex:
                key = bytes.fromhex(args.key_hex)
            else:
                key = generate_key(len(message_bytes))
                print(f"Generated key (hex): {key.hex()}", file=sys.stderr)

            ciphertext = encrypt(message_bytes, key)
            print(f"Ciphertext (hex): {ciphertext.hex()}")
            print(f"Key (hex, SAVE THIS SECURELY): {key.hex()}")
            _print_warning()

        elif args.command == "decrypt":
            ciphertext = bytes.fromhex(args.cipher_hex)
            key = bytes.fromhex(args.key_hex)
            plaintext = decrypt_to_text(ciphertext, key, encoding=args.encoding)
            print(f"Plaintext: {plaintext}")

    except OTPError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Error: invalid hex input ({e})", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
